name: Python autotests

on:
  push:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Tests to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - smoke
          - regression
          - extended

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and Allure
        run: |
          pip install -r requirements.txt
          pip install allure-pytest
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre unzip wget
          wget https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.zip
          unzip -o allure-2.35.1.zip -d /opt/
          sudo ln -sf /opt/allure-2.35.1/bin/allure /usr/bin/allure

      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.deployment_target }}" = "all" ]; then
            pytest --alluredir=allure-results
          else
            pytest -m ${{ github.event.inputs.deployment_target }} --alluredir=allure-results
          fi

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
          
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 1

  publish-report:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: List report files
        run: ls -la allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      - name: Print report URL
        run: |
          echo "Allure Report link:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.repository.name }}/index.html"
