name: Python autotests

on:
  push:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Tests to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - smoke
          - regression
          - extended

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and Allure
        run: |
          pip install -r requirements.txt
          pip install allure-pytest
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre unzip wget
          wget https://github.com/allure-framework/allure2/releases/download/2.35.1/allure-2.35.1.zip
          unzip -o allure-2.35.1.zip -d /opt/
          sudo ln -s /opt/allure-2.35.1/bin/allure /usr/bin/allure

      - name: Run all tests
        if: ${{ github.event.inputs.deployment_target == 'all' }}
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Run smoke tests
        if: ${{ github.event.inputs.deployment_target == 'smoke' }}
        run: pytest -m smoke --alluredir=allure-results
        continue-on-error: true

      - name: Run regression tests
        if: ${{ github.event.inputs.deployment_target == 'regression' }}
        run: pytest -m regression --alluredir=allure-results
        continue-on-error: true

      - name: Run extended tests
        if: ${{ github.event.inputs.deployment_target == 'extended' }}
        run: pytest -m extended --alluredir=allure-results
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 1

  deploy-report:
    needs: run-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
